package gui;


import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MTM5313
 */
public class BikeApp extends javax.swing.JFrame {

    /**
     * Creates new form BikeApp
     */
    public BikeApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/resources/images/bike.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu2 = new MainMenu();
        mainMenu1 = new MainMenu();
        startScreenPanel1 = new StartScreenPanel();
        startScreenPanel2 = new StartScreenPanel();
        mainMenu3 = new MainMenu();
        heartRateScreen2 = new HeartRateScreen();
        startScreenPanel3 = new StartScreenPanel();
        startScreenPanel4 = new StartScreenPanel();
        mainMenu4 = new MainMenu();
        heartRateScreen1 = new HeartRateScreen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bicyle Fitness Tracker");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(startScreenPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));
        getContentPane().add(startScreenPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(mainMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(heartRateScreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BikeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BikeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BikeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BikeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BikeApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private HeartRateScreen heartRateScreen1;
    private HeartRateScreen heartRateScreen2;
    private MainMenu mainMenu1;
    private MainMenu mainMenu2;
    private MainMenu mainMenu3;
    private MainMenu mainMenu4;
    private StartScreenPanel startScreenPanel1;
    private StartScreenPanel startScreenPanel2;
    private StartScreenPanel startScreenPanel3;
    private StartScreenPanel startScreenPanel4;
    // End of variables declaration//GEN-END:variables
}
